name: Build Plugin Release
on: 
  push:
    tags:
      - 1.*

env:
  TAG: $(git describe --tags --abbrev=0)

jobs:
  build:
    name: Build Plugin version
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Create archive
        run: cd sources && tar -czf --exclude=".*" ../helm-kind.tar.gz ./
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./helm-kind.tar.gz
          asset_name: helm-kind.tar.gz
          asset_content_type: application/x-tar
      